name: EcommerceTCADemo
options:
  bundleIdPrefix: com.state.EcommerceTCADemo
targets:
  EcommerceTCADemo:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - EcommerceTCADemo
